name: "Test action"
description: "Action to test Kotlin JS SDK"
inputs:
  required-input:
    description: "A required input"
    required: true
  optional-no-default:
    description: "Optional input"
    required: false
  with-default:
    description: "Input with default"
    required: false
    default: "Test"
  multiline:
    description: "Multiline input"
    required: true
runs:
  using: 'node12'
  main: '../../../test-action/build/dist/index.js'